### ISSUE TITLE
Fails on test data set with error message "Cannot parse record"

### ISSUE THREAD

**Issue by michaelbarton** [rchikhi/docker-gatb-pipeline#1]
I have tested this image on a fastq dataset of 2,000,000 paired reads using the
default task. I have [pasted the log online](https://gist.githubusercontent.com/michaelbarton/1a9a1cbe2fd7bded5e42/raw/log.txt).

**Comment by rchikhi** [comment]
Hi,

Could you please paste me the first 8 lines of the input?
It seems that the first header is

@HISEQ03:379:C2WP8ACXX:7:1101:16697:2006

For paired reads, the pipeline expects that the header of the first
read in a pair ends with "1" or "A". I can fix that but i'm also
curious to see what headers you use for paired reads.

Rayan

**Comment by michaelbarton** [comment]
Here's the first 8 lines from the read file:

@HISEQ03:379:C2WP8ACXX:7:1101:9741:2172 1:N:0:ACTTGA
ACCTTCCCCTGGCCGTCTCGTCGACGGGATTGCCCTTCCTGATGGTCCCCATCACCTACCTGCAGGACGTCGGCGGGGCCGACCCCGACATGGCAGAGATCGAGACGCTGGCGGACGAGTTCGACGCGACCGGCCTCTACCTCTTCCCGC
+
CCCFFFFFHHHHHJIJIJJIHIJJJJJJIJJIJJJJJIIJIJJBGEHIHHFGEDEFFFEDEEEDDBDDDDDDDDDDDD9@<>BDDD>5<9<CDBDBBDCCC?@D?<@BBD@#######################################
@HISEQ03:379:C2WP8ACXX:7:1101:9741:2172 2:N:0:ACTTGA
CACCGCGCCGCTCGCAGTCCCGGTGACGGGATCTTCGGGAACCCCTGCACCTGGCGCGAACATCCGCCCGTGTACCGTCGAGTCGGCCTCGAGGGCGTCGAACGTGAAGAGGTAGATGCCGGTCGCGTCGAACTCGTCCGCCAGCGTCTC
+
CCCFFFFFHHHHHJJJJJJJJJJFHIJJJJHIJJHGHHFFDCDDDDBDCDCCDDDBDDDBBBCDD@DDDB;BBDEDDDDBBDCDDDDD<BB&5>B3@<@B9?<52<8?CCAB+(4:3>>C<B5&005&050888:<8?B9>D########

**Comment by rchikhi** [comment]
Thanks, I see how to fix it. Will follow-up early next week.

**Comment by rchikhi** [comment]
docker-gatb-pipeline has been updated to fix this bug

**Comment by michaelbarton** [comment]
Thanks Rayan. I'm currently working with the CAMI organisers to standardise
the format of short read assembler containers. The project we've started is
bioboxes - https://github.com/bioboxes/rfc

This should mean that once we agree on a standard, all assembler containers
can be used in both CAMI and nucleotid.es.

**Comment by michaelbarton** [comment]
I've created a biobox-compatible Docker image of gatb minia here - https://github.com/bioboxes/gatb-minia
